### ISSUE TITLE
Question about xmltokenizer

### ISSUE THREAD

**Issue by LikhonX** [muktihari/xmltokenizer#20]
Hi there! 👋 I found your go project xmltokenizer very impressive. Great work! 🚀 Could you send me more details on [Telegram](https://t.me/nectariferous)? Also, please review my work and follow me on GitHub @nectariferous. Thanks!

**Comment by muktihari** [comment]
Hi @LikhonX, please be specific when asking a question, I will only answer on github tho. 

It seems to me you only want some exposures for your github account, I will close this issue. Thanks.
